AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing infrastructre for OpenAI ChatGpt Plugin

Parameters:
  RootDomainName:
    Type: String
    Description: Domain name to be used for the API.
    Default: bluecollarverse.com
  RootBucketName:
    Type: String
    Description: Root bucket name
    Default: bluecollarverse

Resources:
  # Certificates
  RootCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref RootDomainName
      ValidationMethod: DNS

  # S3 buckets
  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RootBucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        # ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  RootBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    DependsOn:
      - RootBucket
      - RootCloudFrontDistributionIdentity
    Properties:
      Bucket: !Ref RootBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${RootBucket}/*"
            Principal:
              CanonicalUser: !GetAtt RootCloudFrontDistributionIdentity.S3CanonicalUserId
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${RootBucket}/*"
            Principal: "*"
            Sid: PublicReadGetObject

  RootHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: bluecollarverse.com.

  # Cloud Front
  RootCloudFrontDistributionIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access identity for root s3 bucket

  RootCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - RootCloudFrontDistributionIdentity
      - RootBucket
      - RootCertificate
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref RootDomainName
        Origins:
          - DomainName: !GetAtt RootBucket.DomainName
            Id: MyS3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${RootCloudFrontDistributionIdentity}
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: MyS3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          AllowedMethods:
            - HEAD
            - GET
        ViewerCertificate:
          AcmCertificateArn: !Ref RootCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        HttpVersion: http2

Outputs:
  RootCloudFrontDistributionOutput:
    Description: CloudFront endpoint to add in DNS CNAME record (CNAME  @  <cloud_front_id>  default)
    Value: !GetAtt RootCloudFrontDistribution.DomainName
  RootCloudFrontDistributionIdOutput:
    Description: Root CloudFront Distribution ID
    Value: !Ref RootCloudFrontDistribution
  RootBucketNameOutput:
    Description: Root bucket
    Value: !Ref RootBucket
